apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
  - argocd.exaple.com
  gateways:
    - main-gw
  http:
    - route:
      - destination:
        host: argocd-server.argocd.svc.cluster.local
        port: 
          number: 80
